drivers: qca-wifi-host-cmn: Fix error cause a function declaration is…
… deprecated

../../../../../../kernel/xiaomi/sm8350/drivers/staging/qca-wifi-host-cmn/target_if/core/src/target_if_main.c:98:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.